### ISSUE TITLE
fastest TRAMP method???

### ISSUE THREAD

**Issue by cg505** [kotct/dot#103]
we use ssh, as per emacswiki. but TRAMP itself claims scp is faster. who's right?

also TIL tramp supports adb, lol

**Comment by rye** [comment]
I can definitely point to the fact that TRAMP likes to leave autogenerated commands in my history as a reason to try `scp` over `ssh`.

**Comment by cg505** [comment]
I've been using scp for a while, and it seems pretty much fine. It also seems reasonable to allow TRAMP to dictate the default (which I think is scp). In any case, in emacs 26 you have to type `/-:` to use default protocol anyway, which is a whopping two characters shorter than `/ssh:` if you really want to use ssh. I'll probably open a PR this weekend. It's just like deleting two lines in tramp-c.el.

**Comment by rye** [comment]
SGTM.  Should be transparently no different.
