### ISSUE TITLE
Package cl is deprecated (as of Emacs 27)

### ISSUE THREAD

**Issue by rye** [kotct/dot#141]
With Emacs 27.1, a message is now emitted on startup:

```
Package cl is deprecated
```

We should migrate lines like `(require 'cl)` to `(require 'cl-lib)`.

**Comment by samontea** [comment]
should we do version checking? do we want to keep `26.x` support?

**Comment by rye** [comment]
I don't think version checking would be needed here since `cl-lib` has been included in Emacs since 24.3. The difference is that the old `cl` package doesn't really obey the rule that functions from libraries should use a package prefix, so the new `cl-lib` things are really just prefixed with `cl-` to avoid ambiguity.

There is also a forward compatibility package out there (called `cl-lib`) for older versions of Emacs that we could use, conditionally, based on what version of Emacs the user is using. However, since we don't really test very much with old versions of Emacs, I don't know if we need to.

**Comment by samontea** [comment]
awesome that sounds great. let's do that.

**Comment by samontea** [comment]
There [are some functions whose meaning has changed](http://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=blob;f=packages/cl-lib/cl-lib.el;h=0f05c3e65efe8ccf26db4c8b554133b0696ba7c4;hb=HEAD#l109). What we should do for those is also non obvious. I'll try to get a draft up soon, but this may need some revision/testing.

(Edited to remove a prior misunderstanding)
