### ISSUE TITLE
~/.emacs.d/lisp/kotct-loaddefs.el is loaded on startup

### ISSUE THREAD

**Issue by rye** [kotct/dot#17]
This is annoying.  We shouldn't have this file be loaded into a buffer on startup.

**Comment by cg505** [comment]
?????
It's supposed to be loaded, but as a feature, not into a buffer. I don't think I have this issue.

**Comment by cg505** [comment]
Okay nvm can reproduce. What the fuck?

**Comment by rye** [comment]
same tbh

**Comment by cg505** [comment]
So `update-directory-autolaods` automatically opens it to add autoload info. We should just close it after startup. Do that in init.el.

**Comment by rye** [comment]
Can you fix that @cg505?  I haven't a clue what to do.

**Comment by rye** [comment]
That is to say, if the only way to close this buffer is to find it using `get-buffer` and then kill it, I suppose I could do that.

**Comment by rye** [comment]
But if there's a smarter, dynamic way to do it, you probably know it better than I.

**Comment by cg505** [comment]
Lol nope, I'm pretty sure that's what we have to do. I'll take a look though. Don't think we need `get-buffer`?

**Comment by rye** [comment]
Lemme try it then, haha.

**Comment by cg505** [comment]
Yeah just do `(kill-buffer kotct-loaddefs.el)` at the end of init.el (or after all the `buffer-directory-autoloads` at least).
