### ISSUE TITLE
User Configurations/Hubs

### ISSUE THREAD

**Issue by rye** [kotct/dot#3]
Let's think about user configurations&mdash;they were a key feature of kotct.emacs because they enabled people to quickly switch configurations.

We should think about how we're gonna do this here. @cg505, got any ideas?

I think I'm against having all of this stuck here in this repository, though.  I think having local hubs in a local emacs directory is a good plan&mdash;they could be git submodules of a shared but separate git repository which could get updated by an emacs command, for instance.

**Comment by cg505** [comment]
I like personal git repos: I'll play with the idea a little.

**Comment by rye** [comment]
Work on this has been on the [user-config](/kotct/dot/tree/user-config) branch.  I will leave it to @cg505 to file a PR once he has decided that this is gucci.

**Comment by cg505** [comment]
See #5.

**Comment by rye** [comment]
Done as of ab3cffa08dab34a6d9b195af3b202f2a9f56fbee
