### ISSUE TITLE
Machine-Local Configuration

### ISSUE THREAD

**Issue by cg505** [kotct/dot#30]
Provide some way to have a machine-specific config. Could be used for things like setting executable locations.

**Comment by rye** [comment]
I have my own system for doing this in `duff`. Could be a `~/.emacs-local/` directory that is added to the load-path.

**Comment by rye** [comment]
We should decide where we want this to go. For all intents and purposes, I could see us leaving this in `$XDG_CONFIG_HOME/dot` or `~/.dot-local`.

**Comment by cg505** [comment]
IMO this is pretty high-priority. I think we should just have a gitignored `~/.emacs.d/local/` directory for it.

The main reason we wouldn't go with that approach is if we somehow want to have all machine-local config in the entire dot project within a single directory like `$XDG_CONFIG_HOME/dot` or `~/.dot` or something.
