### ISSUE TITLE
Emacs (25.1.1) Fails on Startup

### ISSUE THREAD

**Issue by rye** [kotct/dot#34]
In CI, Emacs is failing to start up in certain cases due to [line 3 in `user-config-system.el` as of](https://github.com/kotct/dot/blob/5ad51d14ee28a367d55db1e76681f0ce18d18b44/.emacs.d/lisp/user/user-config-system.el#L3) 5ad51d14ee28a367d55db1e76681f0ce18d18b44.

This issue existed prior to this commit as well, but I'm too lazy to bisect.

Since it looks like we don't even use it in that file, I think the fix is to remove that line and *not* require `git`.

**Comment by cg505** [comment]
sorry i think this was an artifact from when i was using a package for git instead of calling the executable directly

**Comment by rye** [comment]
Which approach is better? Using a package or using an executable?

**Comment by cg505** [comment]
I think the current solution is fine.
