### ISSUE TITLE
Better Labels

### ISSUE THREAD

**Issue by rye** [kotct/dot#50]
Our labels are somewhat unspecific and sad.  If we can break things up into more component-wise labels and have priority labels, and use a labelling scheme like [Hyper's](https://github.com/zeit/hyper/labels), I think it'd be much easier to label issues.

**Below are listed the different labelling groups and label names which I have created.**

# Concerns

The `Concerns` set of labels is used for demarcating the scope of the Issue or Pull Request to which they are assigned.

* **Concerns: Dot**
  - For Issues concerning the project as a whole
* **Concerns: Emacs Configuration**
  - For Issues concerning the Emacs Configuration as a whole (but not the entire project, Dot.)
* **Concerns: Emacs/tree/behavior**
  - For Issues concerning stuff in the `behavior` tree of the Emacs configuration
* **Concerns: Emacs/tree/code**
  - For Issues concerning stuff in the `code` tree of the Emacs configuration
* **Concerns: Emacs/tree/file**
  - For Issues concerning stuff in the `file` tree of the Emacs configuration
* **Concerns: Emacs/tree/package**
  - For Issues concerning stuff in the `package` tree of the Emacs configuration
* **Concerns: Emacs/tree/user**
  - For Issues concerning stuff in the `user` tree of the Emacs configuration
* **Concerns: Emacs/tree/visual**
  - For Issues concerning stuff in the `visual` tree of the Emacs configuration

# Is

The `Is` set of labels is used to describe the status or quality of the Issue or Pull Request to which they are assigned.

* **Is: Blocked**
  - For Issues or Pull Requests that cannot be continued until another Issue or Pull Request is resolved
* **Is: Deferred**
  - For Issues or Pull Requests that are side-lined until further notice (see: `Is: On Hold` for another option)
* **Is: Duplicate**
  - For Issues or Pull Requests whose scope and concerns match an extant Issue or Pull Request that has not yet been resolved
* **Is: Invalid**
  - For Issues or Pull Requests that are poorly-written or otherwise deemed invalid
* **Is: Not Fixable**
  - For Issues which cannot be fixed
* **Is: On Hold**
  - For Issues or Pull Requests that are side-lined but may be resumed soon (see: `Is: Deferred` for another option)
* **Is: Question**
  - For Issues that are formulated as questions and are not direct requests
    - A Question label might be used for something hypothetical, but a separate issue should be opened once a decision is reached to specifically track the progress towards resolving the decision.
  - Note: This is _not_ a label of the `Type` set because that set is specifically designated for

# Needs

The `Needs` set of labels is used to describe is used to describe those Issues or Pull Requests which need further action in order to proceed.

* **Needs: Discussion**
  - For Issues or Pull Requests that need discussion in order to proceed
* **Needs: Implementation**
  - For Issues or Pull Requests that need (further) implementation to take place in order to proceed
* **Needs: Investigation**
  - For Issues or Pull Requests that need (further) investigation to take place in order to proceed
* **Needs: Refactoring**
  - For Issues or Pull Requests that need (further) refactoring to take place in order to proceed
* **Needs: Research**
  - For Issues or Pull Requests that need (further) research to take place in order to proceed

# Priority

The `Priority` set of labels is used to describe the approximate priority of the Issue or Pull Request to which they are assigned.

* **Priority: Critical**
  - For Issues or Pull Requests considered to be at extremely high priority
    - e.g. Issues or Pull Requests where direct action is required to solve problems
* **Priority: High**
  - For Issues or Pull Requests considered to be at high priority
    - e.g. Issues or Pull Requests where direct action is strongly preferred over other Issues or Pull Requests
* **Priority: Medium**
  - For Issues or Pull Requests considered to be at medium priority
    - e.g. Issues or Pull Requests where direct action is weakly preferred over other Issues or Pull Requests
* **Priority: Low**
  - For Issues or Pull Requests considered to be at low priority
    - e.g. Issues or Pull Requests where direct action is not preferred over other Issues or Pull Requests

# Type

The `Type` set of labels is used to describe the type of thing that is concerned by the Issue or Pull Request to which they are assigned.

* **Type: Bad Code Style**
  - For Issues concerning bad code style
* **Type: Bad Feature**
  - For Issues concerning bad features (see: `Type: Bug` for another option)
    - e.g. Issues or Pull Requests where existing code improperly uses the system
* **Type: Bad Implementation**
  - For Issues concerning bad implementation of a feature
* **Type: Bad Performance**
  - For Issues concerning bad performance
* **Type: Bug**
  - For Issues concerning bugs (see: `Type: Bad Feature` for another option)
    - e.g. Issues or Pull Requests where the system influences bad behavior in the codebase

# Ungrouped

These labels are specifically ungrouped so that they can be searchable by API bots.

* **Help Wanted**
  - Anything where outside help is wanted

**Comment by cg505** [comment]
idc enough so I'm gonna leave this to you

**Comment by rye** [comment]
Closing because I finished this.  I'm totally open for further suggestions as far as this labelling scheme should go; my only qualms about it have to do with searchability and conciseness, but I think that having thing split up by prefix (e.g. `Concerns:`, `Is:`) helps with this and helps make the labels more easy to understand.

**Comment by rye** [comment]
And for future references, here's the philosophy behind each of these labels and the groupings I created for them.  I will copy-paste this into the Issue body so that we have this, and we could put this in `CONTRIBUTING.md` or some other file.

# Concerns

The `Concerns` set of labels is used for demarcating the scope of the Issue or Pull Request to which they are assigned.

* **Concerns: Dot**
  - For Issues concerning the project as a whole
* **Concerns: Emacs Configuration**
  - For Issues concerning the Emacs Configuration as a whole (but not the entire project, Dot.)
* **Concerns: Emacs/tree/behavior**
  - For Issues concerning stuff in the `behavior` tree of the Emacs configuration
* **Concerns: Emacs/tree/code**
  - For Issues concerning stuff in the `code` tree of the Emacs configuration
* **Concerns: Emacs/tree/file**
  - For Issues concerning stuff in the `file` tree of the Emacs configuration
* **Concerns: Emacs/tree/package**
  - For Issues concerning stuff in the `package` tree of the Emacs configuration
* **Concerns: Emacs/tree/user**
  - For Issues concerning stuff in the `user` tree of the Emacs configuration
* **Concerns: Emacs/tree/visual**
  - For Issues concerning stuff in the `visual` tree of the Emacs configuration

# Is

The `Is` set of labels is used to describe the status or quality of the Issue or Pull Request to which they are assigned.

* **Is: Blocked**
  - For Issues or Pull Requests that cannot be continued until another Issue or Pull Request is resolved
* **Is: Deferred**
  - For Issues or Pull Requests that are side-lined until further notice (see: `Is: On Hold` for another option)
* **Is: Duplicate**
  - For Issues or Pull Requests whose scope and concerns match an extant Issue or Pull Request that has not yet been resolved
* **Is: Invalid**
  - For Issues or Pull Requests that are poorly-written or otherwise deemed invalid
* **Is: Not Fixable**
  - For Issues which cannot be fixed
* **Is: On Hold**
  - For Issues or Pull Requests that are side-lined but may be resumed soon (see: `Is: Deferred` for another option)
* **Is: Question**
  - For Issues that are formulated as questions and are not direct requests
    - A Question label might be used for something hypothetical, but a separate issue should be opened once a decision is reached to specifically track the progress towards resolving the decision.
  - Note: This is _not_ a label of the `Type` set because that set is specifically designated for

# Needs

The `Needs` set of labels is used to describe is used to describe those Issues or Pull Requests which need further action in order to proceed.

* **Needs: Discussion**
  - For Issues or Pull Requests that need discussion in order to proceed
* **Needs: Implementation**
  - For Issues or Pull Requests that need (further) implementation to take place in order to proceed
* **Needs: Investigation**
  - For Issues or Pull Requests that need (further) investigation to take place in order to proceed
* **Needs: Refactoring**
  - For Issues or Pull Requests that need (further) refactoring to take place in order to proceed
* **Needs: Research**
  - For Issues or Pull Requests that need (further) research to take place in order to proceed

# Priority

The `Priority` set of labels is used to describe the approximate priority of the Issue or Pull Request to which they are assigned.

* **Priority: Critical**
  - For Issues or Pull Requests considered to be at extremely high priority
    - e.g. Issues or Pull Requests where direct action is required to solve problems
* **Priority: High**
  - For Issues or Pull Requests considered to be at high priority
    - e.g. Issues or Pull Requests where direct action is strongly preferred over other Issues or Pull Requests
* **Priority: Medium**
  - For Issues or Pull Requests considered to be at medium priority
    - e.g. Issues or Pull Requests where direct action is weakly preferred over other Issues or Pull Requests
* **Priority: Low**
  - For Issues or Pull Requests considered to be at low priority
    - e.g. Issues or Pull Requests where direct action is not preferred over other Issues or Pull Requests

# Type

The `Type` set of labels is used to describe the type of thing that is concerned by the Issue or Pull Request to which they are assigned.

* **Type: Bad Code Style**
  - For Issues concerning bad code style
* **Type: Bad Feature**
  - For Issues concerning bad features (see: `Type: Bug` for another option)
    - e.g. Issues or Pull Requests where existing code improperly uses the system
* **Type: Bad Implementation**
  - For Issues concerning bad implementation of a feature
* **Type: Bad Performance**
  - For Issues concerning bad performance
* **Type: Bug**
  - For Issues concerning bugs (see: `Type: Bad Feature` for another option)
    - e.g. Issues or Pull Requests where the system influences bad behavior in the codebase

# Ungrouped

These labels are specifically ungrouped so that they can be searchable by API bots.

* **Help Wanted**
  - Anything where outside help is wanted

**Comment by cg505** [comment]
goddamn

**Comment by cg505** [comment]
tbh probably bouta tag everything wrong bear with me

**Comment by rye** [comment]
Just look at the descriptions here if you're confused at any point. Hopefully this will be a bit more semantic
