### ISSUE TITLE
Support for Smartparens

### ISSUE THREAD

**Issue by cg505** [kotct/dot#55]
Eventual support for [smartparens](https://github.com/Fuco1/smartparens) is a must at some point. It should be on the radar.

**Comment by cg505** [comment]
Anyone want to take this? I can take it once I finish the testing framework if no one else wants to.

**Comment by rye** [comment]
Sure!

**Comment by cg505** [comment]
assign urself!

**Comment by rye** [comment]
Done.

**Comment by rye** [comment]
(With assignment.)

**Comment by rye** [comment]
I have picked this up again.  @kotct/emacs, should we turn smartparens on globally?

**Comment by samontea** [comment]
lol probably off by default it could be confusing for new users.

**Comment by rye** [comment]
I was actually more asking whether or not it should be turned on for all languages that it supports or if I should manually add a hook for each language.  I'd prefer the former if it's workable.

**Comment by cg505** [comment]
smartparens-like behavior is standard in most IDEs. I don't think it would be confusing or problematic to have smartparens enabled globally by default.

**Comment by rye** [comment]
I agree, that's why I committed it like that. We can always throw in a variable to turn that global setting off.
