### ISSUE TITLE
kotct/user-update-config: Always ask for a username

### ISSUE THREAD

**Issue by rye** [kotct/dot#6]
I'm thinking `M-x kotct/user-update-config` should behave a lot like `C-x C-z` in that it should ask the user for a username to fetch rather than just doing the current one.  I could be wrong about this one, however.

**Comment by cg505** [comment]
I don't get it. Why?  What use case is the

**Comment by cg505** [comment]
ugh sorry, misclicked

**Comment by cg505** [comment]
What use case is this capturing?

**Comment by rye** [comment]
For like when you want to update someone else's thing

**Comment by cg505** [comment]
We could prompt on prefix arg.

**Comment by rye** [comment]
Yeah, that's what I was going for.
