### ISSUE TITLE
Newlines at EOF

### ISSUE THREAD

**Issue by rye** [kotct/dot#64]
Emacs currently seems configured to add newlines at EOF sometimes, but not to all files.  I think we should make it add newlines to all (text) files, since all text files will get griped-about by Git/VC if they don't have newlines at the end.

That's also a pretty standard thing, too.

#### Acceptance Criteria:
- Files are saved with a newline at EOF by default

**Comment by samontea** [comment]
LGTM.

We should make sure that there's a clear function like `kotct/save-without-newline` for cases where a new line would be inappropriate for whatever reason.

**Comment by rye** [comment]
I don't understand why the proposed `kotct/save-without-newline` should be a function in this case.  If anything, this should be a variable that turns defaulting behavior off globally.  Emacs saves files just fine and has a `require-final-newline` variable.  IIRC, this variable is turned on for `prog-mode` but nothing else.  This Issue probably just needs this to go into `fundamental-mode` instead.  Binary files (e.g. images) would probably not need it.

Also, should this newline be added on open or before save?

**Comment by rye** [comment]
See [this ThoughtBot post](https://robots.thoughtbot.com/no-newline-at-end-of-file):

> So, it turns out that, according to POSIX, every text file (including Ruby and JavaScript source files) should end with a `\n`, or “newline” (not “a new line”) character. This acts as the `eol`, or the “end of line” character. It is a line “terminator”.

Since the last line of a file is not any different from any other line of that file, in order to be POSIX-compliant a file must end with a newline. (That is, the newline at the end of that file.)  The only situation I can see to point against this is either (a) someone editing on a non-POSIX-compliant OS, (Windows) or (b) someone editing a binary file. (should be handled by the above; text files should be the only files affected by newline enforcement)

**Comment by samontea** [comment]
But what if I was editing a config file that wasn't supposed to include a new line at the end for whatever reason. That was the spec (created by someone who wasn't aware that newlines at the end of a file were standard etc.).

I was doing something like this earlier this week and emacs added a new line to a file. It didn't appear to effect functionality so I left the newline in, but I would have preferred to have a way to override such defaults in the case that it did effect functionality.

A global toggle seems much more cumbersome (I'd then have to enable it when I start working on another file). It would be best just to have a function that overrides this default for a single save.

**Comment by rye** [comment]
Remember, POSIX [_defines_ a line](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) as:

>**§ 3.206 Line**
>A sequence of zero or more non-&lt;newline&gt; characters plus a terminating &lt;newline&gt; character.

If a config file is non-POSIX-compliant, I would think it smart to add file variables for that particular file, because that particular file is special.  It's worth noting that I have never encountered a config file format where the spec _requires_ there not to be a newline at the end of the file.  Git complains if there is not a newline at the end of the file unless that is turned off, so it seems reasonable to me to assume that most people want there to be newlines at the end of file.  (That's what I prefer, too.)

Do you propose that it'd be best to call a function manually when you want to save?  What keybind should be used if not?  I suppose such a function could just turn `require-final-newline` to `nil` and then reset it back to its previous state.

**Comment by cg505** [comment]
`require-final-newline` is buffer-local fwiw. Doesn't completely address the issue of wanting to do it for a single save, but probably it would make more sense just to do `C-u M-x set-variable RET require-final-newline RET nil RET`. Then you don't have to worry about it until you kill that buffer.

**Comment by rye** [comment]
To implement such a function one could also just `let` `require-final-newline` to `nil` and call `save-buffer` in that body—I think that'd probably work.  This could also just be done via advice around `save-buffer` for a given file.

**Comment by samontea** [comment]
i think @cg505's solution sounds fine to me.

i also have never heard of a requirement that a file doesn't have a newline before the EOF, but it would be nice to have a way of saving that file w/o a new line if one needed to for whatever reason (stylistic, necessity, etc.). if my boss tells me that the file needs to not include a newline before EOF i'd prefer not to have explain to him in how that file wouldn't be posix compliant (à la https://github.com/kotct/dot/issues/64#issuecomment-318871000).

just in general even if our defaults seem perfect for our personal preferences etc. it would be good if we always had a clear way of turning them off in the case of our boss/managers having different preferences.

**Comment by cg505** [comment]
Cool, so no override implementation is needed since the user can set `require-final-newline` to override.

**Comment by rye** [comment]
Exactly.  We typically haven't implemented functions for edge case handling like this particular one, but I'd totally be open to starting to do that.  It shouldn't be an AC for this issue though, because it's an edge case that should be dealt with separately on an as-needed basis.  One can always turn it off.

Or, perhaps it might be best to set `require-final-newline` to `'ask`?  That way you'd get asked every time.  Since files lacking LF at EOF are generally fairly infrequent I would imagine this wouldn't get too annoying.  We can always try that and see how annoying it is.

[From the Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Customize-Save.html):
>**§ 18.3.3: Customizing Saving of Files**
>If the value of the variable `require-final-newline` [is] any other non-`nil` value [not one of the reserved ones] Emacs asks you whether to add a newline. The default is `nil`.

**Comment by cg505** [comment]
nah, i think it's fine as just `t`

**Comment by rye** [comment]
Okay.  I suppose someone could always set it to `'ask` if they want to be asked instead.

**Comment by cg505** [comment]
@rye have you done any work on this or can I just knock it out real quickly rn?

**Comment by rye** [comment]
Woops, yeah, go ahead, @cg505.  I think I had something working but I'll re-assign to you.

**Comment by cg505** [comment]
aight cool
