### ISSUE TITLE
Packup UI update

### ISSUE THREAD

**Issue by samontea** [kotct/dot#66]
Making the `packup` buffer interactive to allow for the user to more easily select a subset of the packages that they wish to update.

It would also help us prepare for the work necessary to complete #56. This can be considered party of that issue.

#### Acceptance Criteria:
- Must allow for user to select packages to update w/i a read only buffer
- Must provide help instructing users how to interact w/ the read only buffer

**Comment by cg505** [comment]
dis gon be sick

**Comment by cg505** [comment]
@samontea Close this issue?

Leaving a couple notes for future reference: support `n` and `p` like magit/dired. recursive dependency resolution?
