### ISSUE TITLE
Add sh-mode customizations

### ISSUE THREAD

**Issue by rye** [kotct/dot#69]
It seems we haven't added support for `sh-mode` yet. That is a thing that should be done.

Known issues needing fixed:
- Spaces are always used

**Comment by cg505** [comment]
What is the goal of this ticket? It's unclear to me at this point.

**Comment by rye** [comment]
To get `sh-mode` configuration implemented.

**Comment by cg505** [comment]
I made some edits. @rye look good?

**Comment by rye** [comment]
Yeah, sure.
