### ISSUE TITLE
kotct/user-switch-username Fails If Previous User Switch Failed

### ISSUE THREAD

**Issue by rye** [kotct/dot#7]
If I switch to a user configuration hub and then back to my own with a syntax error, things break and Emacs complains that, for example if I switch from my own broken hub to `cg505`'s, then try to switch to my own broken hub,

```
cg505-hub is not a currently loaded feature
```

**Comment by cg505** [comment]
In general we are not doing great at failing gracefully rn.

**Comment by rye** [comment]
Hmm. I can't really seem to replicate this again, this might have gotten fixed somewhere along the line.  I'll be sure to reopen if this shows up again.

**Comment by cg505** [comment]
Nope, @samontea and I ran into this yesterday.

**Comment by rye** [comment]
Oh ouch

**Comment by cg505** [comment]
In general, if loading a configuration fails, we don't handle it correctly.
