### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by cg505** [kotct/dot#78]
We should add a code of conduct. My default choice is the [Contributor Covenant](http://contributor-covenant.org/).

**Comment by rye** [comment]
I agree. (I added a `TODO` in the `CONTRIBUTING` file, #59.)

Contributor Covenant sounds fine.  How do we want to handle the contact email?

**Comment by rye** [comment]
In talking with @cg505 recently, we think the best approach might be to just list the two or three emails of active contributors.  @samontea / @cg505, what are the public email addresses you'd like to use in the Code of Conduct?

I could also make `kotct-dot` in Google Groups, if we really don't want who's on that list to be public.  But I think that's part of the benefit of listing each email.

**Comment by rye** [comment]
Here is an example link, which addresses to two separate email addresses: [`mailto:kristofer.rye+a@gmail.com,kristofer.rye+b@gmail.com`](mailto:kristofer.rye+a@gmail.com,kristofer.rye+b@gmail.com)

**Comment by cg505** [comment]
Both solutions are fine. My preferred public email address is christopher.c.cooper@gmail.com, as that is what is on every commit.

Remember that we are not just providing a link, but that the email addresses should also be visible when normally viewing the document. Something of the form [x@x.com, y@y.com, and z@z.com](mailto:x@x.com,y@y.com,z@z.com) is fine.

**Comment by rye** [comment]
I think I prefer the `mailto:` approach because it (i) doesn't require ongoing mailing list maintenance and (ii) makes it abundantly clear who is going to receive the email.  We can note something to the effect of "If you are reporting the conduct of specific contributors, you can remove them from the list of recipients."

**Comment by cg505** [comment]
@samontea confirmed with me that we can use his email merciers.merciers@gmail.com.
